In [9]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_excel('customer_data.xlsx')

In [5]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [6]:
df['workclass'].mode()
df['workclass'] = df['workclass'].fillna(df['workclass'].mode()[0])

In [7]:
df['occupation'] = df['occupation'].fillna(df['occupation'].mode()[0])

In [10]:
le = LabelEncoder()
df['sex'] = pd.get_dummies(df['sex'],drop_first=True,dtype='int')

In [11]:
df['native-country'] = le.fit_transform(df['native-country'])
df['race'] = le.fit_transform(df['race'])

df['relationship'] = le.fit_transform(df['relationship'])
df['occupation'] = le.fit_transform(df['occupation'])
df['marital-status'] = le.fit_transform(df['marital-status'])
df['education'] = le.fit_transform(df['education'])
df['workclass'] = le.fit_transform(df['workclass'])
df['income'] = le.fit_transform(df['income'])

In [12]:
df = df.drop('capital-gain',axis=True)
df = df.drop('capital-loss',axis=True)
df = df.drop('native-country',axis=True)

In [13]:
df.isnull().sum()/len(df)

age               0.0
workclass         0.0
fnlwgt            0.0
education         0.0
education-num     0.0
marital-status    0.0
occupation        0.0
relationship      0.0
race              0.0
sex               0.0
hours-per-week    0.0
income            0.0
dtype: float64

In [14]:
X = df.drop('income',axis=1)
y = df['income']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
knn_classifier = KNeighborsClassifier(n_neighbors=3)

In [17]:
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [18]:
y_pred = knn_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 44.36%